# Linear Algebra

## Lbraries
- Numpy
- numpy.linalg
- scipy.linalg
- Simpy (symbolic algebra)
- CVXOPT (optimization)
- PuLP (linear programing simple)
- matplotlib (plotting)

## Vectors

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import mpl_toolkits.mplot3d


### Plot vectors

In [ ]:
# vector = plt.quiver(0,0,5,5, color='b', units='xy', scale=1)

fig = plt.figure()
ax = fig.add_subplot(1, 1, 1)

plt.quiver(0,0,5,5, color='b', units='xy', scale=1)

# Move left y-axis and bottim x-axis to centre, passing through (0,0)
ax.spines['left'].set_position('center')
ax.spines['bottom'].set_position('center')

# Eliminate upper and right axes
ax.spines['right'].set_color('none')
ax.spines['top'].set_color('none')

# Show ticks in the left and lower axes only
ax.xaxis.set_ticks_position('bottom')
ax.yaxis.set_ticks_position('left')

plt.xlim(-10, 10)
plt.ylim(-10, 10,)
plt.grid()
  
plt.show()

### 3d plot

In [ ]:
def plot_vector(vector,dimension):
    if dimension == '3d':
        assert vector.size == 3
        ax = plt.figure().add_subplot(projection='3d')
        ax.quiver(0,0,0, vector[0],vector[1],vector[2],length=0.1, normalize=True)
    
    if dimension == '2d':
        assert vector.size == 2
        ax = plt.figure().add_subplot(1,1,1)
        ax.quiver(0,0, vector[0],vector[1], color='b', units='xy', scale=1)
        
        # Move left y-axis and bottim x-axis to centre, passing through (0,0)
        ax.spines['left'].set_position('center')
        ax.spines['bottom'].set_position('center')

        # Eliminate upper and right axes
        ax.spines['right'].set_color('none')
        ax.spines['top'].set_color('none')

        # Show ticks in the left and lower axes only
        ax.xaxis.set_ticks_position('bottom')
        ax.yaxis.set_ticks_position('left')
        
        plt.xlim(-5, 5)
        plt.ylim(-5, 5)
        plt.grid()
        

    plt.show()

vector3 = np.array([0.2,0.2,0.1])
vector2 = np.array([1,0])
vector = np.array([0,1])
plot_vector(vector2,'2d')
plot_vector(vector,'2d')

## Vector operations

Vectors: $ x = (x_{1}, ... , x_{n})$

addition:$ x + y =  \left[ {\begin{array}{c} x_{1} + y_{1} \\ x_{2} + y_{2} \\ . \\ . \\ x_{n} + y_{n}  \end{array}} \right]$ ; substraction: $x - y  = \left[ {\begin{array}{c} x_{1} - y_{1} \\ x_{2} - y_{2} \\ . \\ . \\ x_{n} - y_{n}  \end{array}} \right]$; Multiplication: $\tau x = \left[ {\begin{array}{c} \tau x_{1} \\ \tau x_{2} \\ . \\ . \\ \tau x_{n}   \end{array}} \right]$ 

Scalar product: $<x,y> = \sum_{i=1}^{n}x_{i}y_{i}$ 

Vector norm: $||x|| = \sqrt{<x,x>} = ( \sum_{i=1}^{n}x_{i}^{2} )^{1/2}$


In [ ]:
# vector python.
vector = [1, 2, 3, 4]

# vector numpy
import numpy as np
vector1 = np.ones(3) #vector just ones
vector2 = np.array([1, 2, 4]) #vector with arrays
vector3 = np.arange(1,4) # vector with range of 1-3 ; result = array([1,2,3])

print("vector1:", vector1)
print("vector2:", vector2)
print("vector3:", vector3)

In [ ]:
x = np.array([1, 2, 3])
y = np.array([1, 2, 3])
 
# add
suma = x + y # result array([2, 4, 6])
print("suma:", suma)

# subs
resta = x - y # result array([0, 0, 0])
print("resta:", resta)

# multiplication
multiplicacion = x * 2 #result array([2, 4, 6])
print("multiplicación:", multiplicacion)

# scalar product
prod_escalar1 = x @ y # result 14
prod_escalar2 = sum(x * y), np.dot(x,y) # result (14,14)
print("producto escalar 1:", prod_escalar1)
print("producto escalar 2:", prod_escalar2)

# vector norm
normal = np.linalg.norm(x) #result 3.7416...
normal2 = np.sqrt(x @ x)
print("normal:", normal)
print("norma2:", normal2)


## Matrix

$A  = \left[ {\begin{array}{cccc} a_{11} & a_{12} & ... & a_{1k} \\  a_{21} & a_{22} & ... & a_{2k} \\ . & . & & . \\ . & . & & . \\ a_{n1} & a_{n2} & ... & a_{nk}  \end{array}} \right]$

add: $A + B = \left [ \begin{array}{ccc} a_{11} & ... & a_{1k} \\ . & . & . \\ . & . & . \\ a_{n1} & ... & a_{nk}   \end{array} \right] + \left [ \begin{array}{ccc} b_{11} & ... & b_{1k} \\ . & . & . \\ . & .& .& \\  b_{n1} & ... & b_{nk} \end{array} \right ] = \left [ \begin{array}{cccc} a_{11} + b_{11} & ... & a_{1k} + b_{1k} \\ . & . & . & \\ . & . & . \\ a_{n1} + b_{n1} & ... & a_{nk} + b_{nk} \end{array} \right ]$

subs: $A - B = \left [ \begin{array}{ccc} a_{11} & ... & a_{1k} \\ . & . & . \\ . & . & . \\ a_{n1} & ... & a_{nk}   \end{array} \right] + \left [ \begin{array}{ccc} b_{11} & ... & b_{1k} \\ . & . & . \\ . & .& .& \\  b_{n1} & ... & b_{nk} \end{array} \right ] = \left [ \begin{array}{cccc} a_{11} - b_{11} & ... & a_{1k} - b_{1k} \\ . & . & . & \\ . & . & . \\ a_{n1} - b_{n1} & ... & a_{nk} - b_{nk} \end{array} \right ]$
  
Multiplication: $\tau A =  \left [ \begin{array}{cccc} \tau a_{11} & ... & \tau a_{1k} \\ . & . & . & \\ . & . & . \\ \tau a_{n1} & ... & \tau a_{nk} \end{array} \right ]$


$AxB \not= BxA$

In [ ]:
A = np.array([[1, 3, 2],
              [1, 0, 0],
              [1, 2, 2]])

B = np.array([[1, 0, 5],
              [7, 5, 0],
              [2, 1, 1]])

# add
suma = A + B
# # result
# array([[2, 3, 7],
#        [8, 5, 0],
#        [3, 3, 3]])
print("suma:", suma)

# subs
resta = A - B
# result
# array([[ 0,  3, -3],
#        [-6, -5,  0],
#        [-1,  1,  1]])
print("resta:", resta)

# scalar multiplication
mul_escalar = A * 2
# result
# array([[2, 6, 4],
#        [2, 0, 0],
#        [2, 4, 4]])
print("multiplicación:", mul_escalar)

# matrix dimension
dim = A.shape
# result (3,3)
print("dimensión:", dim)

# matrix size elements
elementos = A.size 
# result 9
print("elementos de la matriz:", elementos)

# matrix multiplication
A = np.arange(1, 13).reshape(3, 4) #dim 3x4
#Result
# array([[ 1,  2,  3,  4],
#        [ 5,  6,  7,  8],
#        [ 9, 10, 11, 12]])
print("A", A)

B = np.arange(8).reshape(4,2) #dim 4x2
#result
# array([[0, 1],
#        [2, 3],
#        [4, 5],
#        [6, 7]])
print("B:", B)

mul_matrices = A @ B 
# result
# array([[ 40,  50],
#        [ 88, 114],
#        [136, 178]])
print("multiplicación de matrices:", mul_matrices)



### Identity matrix
It is the equivalent of the number 1 or neutral element. It is a square matrix, that is, the same number of columns and rows. It is represented by $I$ and its diagonal is composed of ones.

### Inverse matrix
It is that square matrix $A^{-1}$ that when you perform the multiplication $AxA^{-1}$ is equal to the identity matrix, $AxA^{-1} = A^{-1}xA = I$ . In the event that a matrix does not contain an inverse matrix, said matrix will be a singular matrix. A matrix is singular if and only if its determinant is null.

### Transposed matrix
It is a matrix in which the rows become columns and the columns become rows. $A^{T}$

In [ ]:
A = np.array([[4, 7],
              [2, 6]])

# Identity matrix 2x2
I = np.eye(2)
# result
# array([[1., 0.],
#        [0., 1.]])
print("matriz identidad:", I)

# determinant
D = np.linalg.det(A) # result D = 10
print("determinante:", D)

# inverse matrix
A_inv = np.linalg.inv(A)
#result
# array([[ 0.6, -0.7],
#        [-0.2,  0.4]])
print("matriz inversa:", A_inv)

#traspose
transpuesta = np.transpose(A) 
# result 
# array([[4, 2],
#        [7, 6]])
print("matriz transpuesta:", transpuesta)


## Linear systems equations
we can use **solve()** method to solve linear systems equations.

$\begin{array}{rcl}
     x+ 2y + 3z & = & 6
  \\ 2x + 5y + 2z & = & 4
  \\ 6x - 3y + z & = & 2
\end{array}
$

In [ ]:
# coeficient matrix
A = np.array([[1, 2, 3],
              [2, 5, 2],
              [6, -3, 1]])

# result matrix
b = np.array([6, 4, 2])

# solution
x = np.linalg.solve(A, b)
#resultado array([0., 0., 2.])
print("resultado:", x)

# testing 
resultado = A @ x == b
print("confirmar resultados:", resultado)
# result array([ True,  True,  True])

# Space transformations

In [ ]:
import torch
import torch.nn as nn
from matplotlib import pyplot as plt
import numpy as np

## dark mode 

In [ ]:
# create plot styles and tools from alfredo canziani notebook
plt.style.use(['dark_background', 'bmh'])
plt.rc('axes', facecolor='k')
plt.rc('figure', facecolor='k')
plt.rc('figure', figsize=(10,10), dpi=50)


## Usefull methods

In [ ]:
def plot_bases(bases, width=0.04):
    bases = bases.cpu()
    bases[2:] -= bases[:2]
    plt.arrow(*bases[0], *bases[2], width=width, color=(1,0,0), zorder=10, alpha=1., length_includes_head=True)
    plt.arrow(*bases[1], *bases[3], width=width, color=(0,1,0), zorder=10, alpha=1., length_includes_head=True)

def show_scatterplot(X, colors, title=''):
    colors = colors.cpu().numpy()
    X = X.cpu().numpy()
    plt.figure()
    plt.axis('equal')
    plt.scatter(X[:, 0], X[:, 1], c=colors, s=30)
    plt.grid(True)
    plt.title(title)
    plt.axis('off')

## Generate 2d data

In [ ]:
n_points = 1000 #number of points
X = torch.randn(n_points, 2) #data points
colors = X[:, 0]
OI = torch.cat((torch.zeros(2, 2), torch.eye(2)))

show_scatterplot(X, colors, title='X')
plot_bases(OI)

## Generate random matrix

In [ ]:
# Generate a random matrix W = U[[s1, 0][0, s2]]V.T
# Compute y = Wx
# larager singular  values stretch the points and smarllers push them together
# U: rotate the points, V reflect the points

for i in range(5):
    # create a random matrix
    W = torch.randn(2, 2) 
    # transform points
    Y = X @ W.t()
    # compute singular values
    U, S, V = torch.svd(W)
    # plot transformed points
    show_scatterplot(Y, colors, title='y = Wx, singular values : [{:.3f}, {:.3f}]'.format(S[0], S[1]))
    # transform the basis
    new_OI = OI @ W.t()
    # plot old and new basis
    plot_bases(OI)
#     plot_bases(new_OI)

## Linear transformation with pytorch

In [ ]:
model = nn.Sequential(nn.Linear(2, 2, bias=False))

with torch.no_grad():
    Y = model(X)
    show_scatterplot(Y, colors)
    plot_bases(model(OI))

## non-linear trasnformation can curve the space


In [ ]:
z = torch.linspace(-10, 10, 101)
s = torch.tanh(z)
plt.plot(z.numpy(), s.numpy())
plt.title('tanh() non linearity')

In [ ]:
show_scatterplot(X, colors, title='X')
plot_bases(OI)

model = nn.Sequential(
        nn.Linear(2, 2, bias=False), #linear function
        nn.Tanh() #non-linear function
)

for s in range(1, 5):
    W = s * torch.eye(2)
    model[0].weight.data.copy_(W)
    Y = model(X).data
    show_scatterplot(Y, colors, title=f'f(x), s={s}')
    plot_bases(OI, width=0.01)

## 1 layer NN with random weights (not trained)

In [ ]:
show_scatterplot(X, colors, title='x')
n_hidden = 5

for i in range(3):
    model = nn.Sequential(
            nn.Linear(2, n_hidden), 
            nn.Tanh(), #can be nn.ReLU()
            nn.Linear(n_hidden, 2)
        )

    with torch.no_grad():
        Y = model(X)
    show_scatterplot(Y, colors, title='f(x)')
#     plot_bases(OI)

## Deeper neural network

In [ ]:
show_scatterplot(X, colors, title='x')
n_hidden = 5

NL = nn.ReLU()
# activation = nn.Tanh()

for i in range(3):
    model = nn.Sequential(
        nn.Linear(2, n_hidden), 
        activation, 
        nn.Linear(n_hidden, n_hidden), 
        activation, 
        nn.Linear(n_hidden, n_hidden), 
        activation, 
        nn.Linear(n_hidden, n_hidden), 
        activation, 
        nn.Linear(n_hidden, 2)
    )

    with torch.no_grad():
        Y = model(X).detach()
    show_scatterplot(Y, colors, title='f(x)')