# Value Iteraction

<img src="./assets/valueIteraction.png" alt="Value iteraction" title="Value Iteraction algorithm" width="500" height="500"/>


In [62]:
# Import tools

import numpy as np
import pprint
import sys
if "../" not in sys.path:
  sys.path.append("../")
from Myenviroments.gridWorld import GridWorldEnv
import gym

In [63]:
# create environment

pp = pprint.PrettyPrinter(indent=2)
env = GridWorldEnv()

In [64]:
# value iteraction function

def valueIteraction(enviroment,theta=0.0001,discountFactor=1.0):
    """
    #TODO: add definition
    #TODO: create a own argmax because it not works
    #TODO: comment the code
    """
    V = np.zeros(env.nS) #value function
    policy = np.zeros([env.nS,env.nA])
    A = np.zeros(env.nA) #best actions 
    pi = np.zeros(env.nS)

    while True:

        delta = 0

        for s in range(env.nS):

            v = V[s] #best action value
            
            #ecuation
            for a in range(env.nA):
                for p, nextS, reward, done in enviroment.P[s][a]:
                    A[a] = p * (reward + discountFactor * V[nextS])

            V[s] = max(A)

            delta = max(delta,np.abs(v-V[s]))

        if delta < theta:
            break

        #find the optimal value function
    for s in range(env.nS):

        for a in range(env.nA):
            for p, nextS, reward, done in enviroment.P[s][a]:
                A[a] = p * (reward + discountFactor * V[nextS])

        bestAction = np.argmax(A) 
        policy[s,bestAction] = 1.0

    

    return policy,V
    

In [65]:
# test results

policy,v = valueIteraction(env)

print('policy: ')
print(policy)
print("")
print('values function:')
print(v)
print("")
print('value function reshape')
print(v.reshape(env.shape))

policy: 
[[1. 0. 0. 0.]
 [0. 0. 0. 1.]
 [0. 0. 0. 1.]
 [0. 1. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [1. 0. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 1. 0.]
 [1. 0. 0. 0.]]

values function:
[ 0. -1. -2. -3. -1. -2. -3. -2. -2. -3. -2. -1. -3. -2. -1.  0.]

value function reshape
[[ 0. -1. -2. -3.]
 [-1. -2. -3. -2.]
 [-2. -3. -2. -1.]
 [-3. -2. -1.  0.]]
